//! Lock file helpers for pinning local schema resources by URI and SHA-256.

use std::fmt::Write as _;

use serde::{Deserialize, Serialize};

/// A single locked resource entry: URI and SHA-256 digest pair.
///
/// The field name `digest` matches the resolver's [`schemaforge_resolver::LockEntry`]
/// so the two lock formats share the same key names.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LockEntry {
    /// Resource URI (e.g. `file:///path/to/schema.json`).
    pub uri: String,
    /// SHA-256 hex digest of the resource bytes at lock time.
    pub digest: String,
}

impl LockEntry {
    /// Create a new lock entry.
    #[must_use]
    pub fn new(uri: impl Into<String>, digest: impl Into<String>) -> Self {
        Self {
            uri: uri.into(),
            digest: digest.into(),
        }
    }
}

/// Serialise a slice of [`LockEntry`] values to TOML text.
///
/// The output uses `[[resource]]` array-of-tables so it can be parsed back
/// by any TOML 1.0 library.
#[must_use]
pub fn format_lock_toml(entries: &[LockEntry]) -> String {
    let mut out = String::from("# Generated by schemaforge lock. Do not edit manually.\n\n");
    for entry in entries {
        write!(
            out,
            "[[resource]]\nuri    = \"{}\"\ndigest = \"{}\"\n\n",
            entry.uri, entry.digest
        )
        .unwrap_or(());
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lock_entry_roundtrip() {
        let e = LockEntry::new("file:///schema.json", "abc123");
        assert_eq!(e.uri, "file:///schema.json");
        assert_eq!(e.digest, "abc123");
    }

    #[test]
    fn format_lock_toml_output() {
        let entries = [
            LockEntry::new("file:///a.json", "aaa"),
            LockEntry::new("file:///b.json", "bbb"),
        ];
        let toml = format_lock_toml(&entries);
        assert!(toml.contains("[[resource]]"));
        assert!(toml.contains(r#"uri    = "file:///a.json""#));
        assert!(toml.contains(r#"digest = "bbb""#));
    }
}
